package entities;
// Generated 02-mar-2018 20:08:31 by Hibernate Tools 4.3.1



/**
 * Historial generated by hbm2java
 */
public class Historial  implements java.io.Serializable {


     private Integer idhistorial;
     private Sudoku sudoku;
     private Usuario usuario;
     private Integer time;

    public Historial() {
    }

    public Historial(Sudoku sudoku, Usuario usuario, Integer time) {
       this.sudoku = sudoku;
       this.usuario = usuario;
       this.time = time;
    }
   
    public Integer getIdhistorial() {
        return this.idhistorial;
    }
    
    public void setIdhistorial(Integer idhistorial) {
        this.idhistorial = idhistorial;
    }
    public Sudoku getSudoku() {
        return this.sudoku;
    }
    
    public void setSudoku(Sudoku sudoku) {
        this.sudoku = sudoku;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Integer getTime() {
        return this.time;
    }
    
    public void setTime(Integer time) {
        this.time = time;
    }

   

}


