package entities;
// Generated 02-mar-2018 20:08:31 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sudoku generated by hbm2java
 */
public class Sudoku  implements java.io.Serializable {


     private Integer idSudoku;
     private int nivel;
     private String descripcion;
     private String problema;
     private String solucion;
     private Set historials = new HashSet(0);

    public Sudoku() {
    }

	
    public Sudoku(int nivel, String descripcion, String problema, String solucion) {
        this.nivel = nivel;
        this.descripcion = descripcion;
        this.problema = problema;
        this.solucion = solucion;
    }
    public Sudoku(int nivel, String descripcion, String problema, String solucion, Set historials) {
       this.nivel = nivel;
       this.descripcion = descripcion;
       this.problema = problema;
       this.solucion = solucion;
       this.historials = historials;
    }
   
    public Integer getIdSudoku() {
        return this.idSudoku;
    }
    
    public void setIdSudoku(Integer idSudoku) {
        this.idSudoku = idSudoku;
    }
    public int getNivel() {
        return this.nivel;
    }
    
    public void setNivel(int nivel) {
        this.nivel = nivel;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getProblema() {
        return this.problema;
    }
    
    public void setProblema(String problema) {
        this.problema = problema;
    }
    public String getSolucion() {
        return this.solucion;
    }
    
    public void setSolucion(String solucion) {
        this.solucion = solucion;
    }
    public Set getHistorials() {
        return this.historials;
    }
    
    public void setHistorials(Set historials) {
        this.historials = historials;
    }

    @Override
    public String toString() {
        return "Sudoku{" + "idSudoku=" + idSudoku + ", nivel=" + nivel + ", descripcion=" + descripcion + ", problema=" + problema + ", solucion=" + solucion + ", historials=" + historials + '}';
    }




}


